//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeConversionService.ConverTemperarture {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConverTemperarture.IConvertTemperature")]
    public interface IConvertTemperature {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/CelciusToFahrenheit", ReplyAction="http://tempuri.org/IConvertTemperature/CelciusToFahrenheitResponse")]
        string CelciusToFahrenheit(decimal celcius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/CelciusToFahrenheit", ReplyAction="http://tempuri.org/IConvertTemperature/CelciusToFahrenheitResponse")]
        System.Threading.Tasks.Task<string> CelciusToFahrenheitAsync(decimal celcius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/FahrenheitToCelcius", ReplyAction="http://tempuri.org/IConvertTemperature/FahrenheitToCelciusResponse")]
        string FahrenheitToCelcius(decimal Fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertTemperature/FahrenheitToCelcius", ReplyAction="http://tempuri.org/IConvertTemperature/FahrenheitToCelciusResponse")]
        System.Threading.Tasks.Task<string> FahrenheitToCelciusAsync(decimal Fahrenheit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConvertTemperatureChannel : ConsumeConversionService.ConverTemperarture.IConvertTemperature, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertTemperatureClient : System.ServiceModel.ClientBase<ConsumeConversionService.ConverTemperarture.IConvertTemperature>, ConsumeConversionService.ConverTemperarture.IConvertTemperature {
        
        public ConvertTemperatureClient() {
        }
        
        public ConvertTemperatureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertTemperatureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertTemperatureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertTemperatureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CelciusToFahrenheit(decimal celcius) {
            return base.Channel.CelciusToFahrenheit(celcius);
        }
        
        public System.Threading.Tasks.Task<string> CelciusToFahrenheitAsync(decimal celcius) {
            return base.Channel.CelciusToFahrenheitAsync(celcius);
        }
        
        public string FahrenheitToCelcius(decimal Fahrenheit) {
            return base.Channel.FahrenheitToCelcius(Fahrenheit);
        }
        
        public System.Threading.Tasks.Task<string> FahrenheitToCelciusAsync(decimal Fahrenheit) {
            return base.Channel.FahrenheitToCelciusAsync(Fahrenheit);
        }
    }
}
